apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: "{{ docker_username}}/{{ docker_image_name }}:{{ docker_image_tag }}"
          ports:
            - containerPort: 8081
