apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '${Label}'
  template:
    metadata:
      labels:
        app: '${Label}'
    spec:
      containers:
        - name: my-container
          image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
          ports:
            - containerPort: 8081
